# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='social_id',
            field=models.CharField(db_index=True, default=0, max_length=100, unique=True),
        ),
    ]
